document.writeln("<!-- footer 开始 -->");
document.writeln("<footer class=\'footer\'>");
document.writeln("    <div class=\'footer_box\'>");
document.writeln("        <ul>");
document.writeln("            <p>新手指南</p>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>购物流程</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>会员尊享</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>常见问题</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>指圈测量</a></li>");
document.writeln("        </ul>");
document.writeln("        <ul>");
document.writeln("            <p>物流配送</p>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>配送方式</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>配送服务</a></li>");
document.writeln("        </ul>");
document.writeln("        <ul>");
document.writeln("            <p>售后服务</p>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>退款说明</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>保养物语</a></li>");
document.writeln("        </ul>");
document.writeln("        <ul>");
document.writeln("            <p>关于我们</p>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>品牌介绍</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>销售渠道</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>联系我们</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>加入我们</a></li>");
document.writeln("        </ul>");
document.writeln("        <ul>");
document.writeln("            <p>关注我们</p>");
document.writeln("            <li class=\'f_weixin\'><a href=\'\' target=\'_blank\'>微信</a></li>");
document.writeln("            <li class=\'f_weibo\'><a href=\'\' target=\'_blank\'>微博</a></li>");
document.writeln("        </ul>");
document.writeln("        <dl class=\'new_r\'>");
document.writeln("            <dt></dt>");
document.writeln("            <dd>");
document.writeln("                <p>微信关注roseonly <br>激活会员，立即领取</p>");
document.writeln("                <h2>50元优惠券</h2>");
document.writeln("                <div></div>");
document.writeln("            </dd>");
document.writeln("        </dl>");
document.writeln("        <div class=\'footer-yyzz\' style=\'display:none;\'>");
document.writeln("            <a href=\'\' target=\'_blank\'>营业执照</a>");
document.writeln("            <a href=\'\' target=\'_blank\'>食品证副本</a>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'foot-nav\'>");
document.writeln("        京ICP备13007738号 京公网安备11010502023922<br>诺誓（北京）商业股份有限公司");
document.writeln("    </div>");
document.writeln("</footer>");
document.writeln("<!-- footer 结束 -->");
document.writeln("<!-- 返回首页 -->");
document.writeln("<div id=\'back-to-top\' style=\'display: block;\'>");
document.writeln("    <a class=\'go_top\' href=\'#top\'><img src=\'https://www.roseonly.com.cn/upload/syspic_new/14703637041003761.svg\'>");
document.writeln("    </a>");
document.writeln("</div>");
document.writeln("<!-- 客服 -->");
document.writeln("<div id=\'zhichiBtnBox\'>");
document.writeln("    <a id=\'zhichiBtn\'>");
document.writeln("        <img src=\'https://www.roseonly.com.cn/upload/syspic_new/14703636967439422.svg\'>");
document.writeln("    </a>");
document.writeln("    <div class=\'mes_content\' style=\'display: none;\'>");
document.writeln("        <div class=\'mes_icon\'>");
document.writeln("            <div class=\'tel_sj\'><img src=\'https://www.roseonly.com.cn/upload/syspic_new/14769441969842358.png\' alt=\'\'>");
document.writeln("            </div>");
document.writeln("            <div class=\'tel_icon\'>");
document.writeln("                <p class=\'tel_txt\'>联系电话</p>");
document.writeln("                <p class=\'tel_phone\'>400-1314-520</p>");
document.writeln("            </div>");
document.writeln("            <div class=\'tel_line\'></div>");
document.writeln("            <div class=\'zxkf_txt\'>");
document.writeln("                <a id=\'btn_onlineZhichi\'>在线客服</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<!-- 二维码 -->");
document.writeln("<div id=\'ewmBox\'>");
document.writeln("    <a id=\'ewm\'>");
document.writeln("        <img src=\'https://www.roseonly.com.cn/upload/syspic_new/14945591270622918.svg\'>");
document.writeln("    </a>");
document.writeln("    <div class=\'ewm_content\' style=\'display: none;\'></div>");
document.writeln("</div>");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("    $(\'#zhichiBtnBox\').hover(function () {");
document.writeln("        $(\'.mes_content\').css({");
document.writeln("            display: \'block\'");
document.writeln("        })");
document.writeln("    }, function () {");
document.writeln("        $(\'.mes_content\').css({");
document.writeln("            display: \'none\'");
document.writeln("        })");
document.writeln("    });");
document.writeln("    $(\'#ewmBox\').hover(function () {");
document.writeln("        $(\'.ewm_content\').css({");
document.writeln("            display: \'block\'");
document.writeln("        })");
document.writeln("    }, function () {");
document.writeln("        $(\'.ewm_content\').css({");
document.writeln("            display: \'none\'");
document.writeln("        })");
document.writeln("    });");
document.writeln("</script>");
document.writeln("<script>");
document.writeln("    $(function () {");
document.writeln("        $(\'.go_top\').on(\'click\', function () {");
document.writeln("            // 元素距离页面顶部的高度");
document.writeln("            var top = $(\'#top\').offset().top;");
document.writeln("            $(\'html,body\').animate({");
document.writeln("                scrollTop: top");
document.writeln("            }, 600);");
document.writeln("        });");
document.writeln("    });");
document.writeln("</script>");