document.writeln("<!-- footer 开始 -->");
document.writeln("<footer class=\'footer\'>");
document.writeln("    <div class=\'footer_box\'>");
document.writeln("        <ul>");
document.writeln("            <p>新手指南</p>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>购物流程</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>会员尊享</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>常见问题</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>指圈测量</a></li>");
document.writeln("        </ul>");
document.writeln("        <ul>");
document.writeln("            <p>物流配送</p>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>配送方式</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>配送服务</a></li>");
document.writeln("        </ul>");
document.writeln("        <ul>");
document.writeln("            <p>售后服务</p>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>退款说明</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>保养物语</a></li>");
document.writeln("        </ul>");
document.writeln("        <ul>");
document.writeln("            <p>关于我们</p>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>品牌介绍</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>销售渠道</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>联系我们</a></li>");
document.writeln("            <li><a href=\'\' target=\'_blank\'>加入我们</a></li>");
document.writeln("        </ul>");
document.writeln("        <ul>");
document.writeln("            <p>关注我们</p>");
document.writeln("            <li class=\'f_weixin\'><a href=\'\' target=\'_blank\'>微信</a></li>");
document.writeln("            <li class=\'f_weibo\'><a href=\'\' target=\'_blank\'>微博</a></li>");
document.writeln("        </ul>");
document.writeln("        <dl class=\'new_r\'>");
document.writeln("            <dt></dt>");
document.writeln("            <dd>");
document.writeln("                <p>微信关注roseonly <br>激活会员，立即领取</p>");
document.writeln("                <h2>50元优惠券</h2>");
document.writeln("                <div></div>");
document.writeln("            </dd>");
document.writeln("        </dl>");
document.writeln("        <div class=\'footer-yyzz\' style=\'display:none;\'>");
document.writeln("            <a href=\'\' target=\'_blank\'>营业执照</a>");
document.writeln("            <a href=\'\' target=\'_blank\'>食品证副本</a>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'foot-nav\'>");
document.writeln("        京ICP备13007738号 京公网安备11010502023922<br>诺誓（北京）商业股份有限公司");
document.writeln("    </div>");
document.writeln("</footer>");
document.writeln("<!-- footer 结束 -->");