document.writeln("<!-- 头部 -->");
document.writeln("<header id=\'header\'>");
document.writeln("    <!--  -->");
document.writeln("    <div class=\'head\'>");
document.writeln("        <!-- left -->");
document.writeln("        <div class=\'div_lang\'><label>CN</label>");
document.writeln("            <ul>");
document.writeln("                <li class=\'cn\'><a href=\'index.html\'>CN</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <a href=\'index.html\' class=\'roseonly-logo\' id=\'tag_roseonly\'></a>");
document.writeln("        <!-- right -->");
document.writeln("        <ul class=\'right\'>");
document.writeln("            <!-- 登录/注册 -->");
document.writeln("            <li class=\'right_dlzc\'>");
document.writeln("                <div class=\'h_dlzc\'></div>");
document.writeln("                <div class=\'header_toplogin_con\'>");
document.writeln("                    <div class=\'header_toplogin\'>");
document.writeln("                        <div>");
document.writeln("                            <div class=\'header_dlzc\'>");
document.writeln("                                <a href=\'./toLogin.html\' class=\'unlogin\' rel=\'nofollow\'>");
document.writeln("                                    <span id=\'h_font\' class=\'h_font\'>登录</span>");
document.writeln("                                </a>");
document.writeln("                                <span class=\'h_line\'>|</span>");
document.writeln("                                <a href=\'./toReg.html\' class=\'unlogin zc_flr \' rel=\'nofollow\'>");
document.writeln("                                    <span id=\'h_font\' class=\'h_font\'>注册</span>");
document.writeln("                                </a>");
document.writeln("                                <a style=\'display:none\' href=\'\' class=\'login\'>");
document.writeln("                                    <span class=\'h_font\'>个人中心</span>");
document.writeln("                                </a>");
document.writeln("                                <a style=\'display:none\' href=\'javascript:void(0)\' onclick=\'logout();\'");
document.writeln("                                    class=\'login zc_flr\'>");
document.writeln("                                    <span class=\'h_font\'>退出</span>");
document.writeln("                                </a>");
document.writeln("                            </div>");
document.writeln("                            <dl class=\'top_ewm\'>");
document.writeln("                                <dt></dt>");
document.writeln("                                <dd>");
document.writeln("                                    <h1>立即领取 50元 优惠券</h1>");
document.writeln("                                    <p> 微信关注roseonly诺誓商城,<br>");
document.writeln("                                        激活成为会员即可领取,<br>");
document.writeln("                                        更多会员专享活动等你参与！");
document.writeln("                                    </p>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("            <li class=\'h_dlzc_line\'></li>");
document.writeln("            <!-- 购物车 -->");
document.writeln("            <li class=\'h_right-shop\'>");
document.writeln("                <a href=\'../html/cart.html\' class=\'right-shop\' rel=\'nofollow\'></a>");
document.writeln("            </li>");
document.writeln("            <!-- 购物车商品数量 -->");
document.writeln("            <li id=\'cartNum\' class=\'cartNum\'>(0)</li>");
document.writeln("            <li class=\'h_dlzc_line\'></li>");
document.writeln("            <!-- 地址 -->");
document.writeln("            <li style=\'float:right\'><a href=\'地址\' target=\'_blank\' class=\'std\'></a></li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</header>");
document.writeln("<!-- 头部结束 -->");
document.writeln("");
document.writeln("<!-- logo -->");
document.writeln("<div class=\'logo-container\'>");
document.writeln("    <a href=\'index1.html\' class=\'logo_nbtn\'></a>");
document.writeln("</div>");
document.writeln("<!-- logo结束 -->");
document.writeln("");
document.writeln("<!-- 导航栏 开始-->");
document.writeln("<div class=\'nav-container\' id=\'topmenus\'>");
document.writeln("    <div class=\'nav-bar\'>");
document.writeln("        <ul id=\'nav\' class=\'cl-effect-1\'>");
document.writeln("            <li><a href=\'../html/index1.html\' class=\'topmenu_1\'>新品上市</a></li>");
document.writeln("            <li><a href=\'../html/index1.html\' class=\'topmenu_1\'>爱礼推荐");
document.writeln("                    <div class=\'menus2\'>");
document.writeln("                        <div class=\'menus\'>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>场合</span> <a href=\'\'> <span>生日</span>");
document.writeln("                                </a> <a href=\'\'> <span>纪念日</span> </a> <a href=\'\'> <span>表白</span> </a> <a href=\'\'>");
document.writeln("                                    <span>求婚</span> </a> </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>人群</span> <a href=\'\'> <span>送给她</span>");
document.writeln("                                </a> <a href=\'\'> <span>送给他</span> </a>");
document.writeln("                                <a href=\'\'> <span>送母亲</span> </a> <a href=\'\'> <span>送父亲</span> </a>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>品类</span> <a href=\'\'>");
document.writeln("                                    <span>玫瑰礼盒<label></label></span> </a> <a href=\'\'> <span>鲜花玫瑰<label");
document.writeln("                                            class=\'hot\'></label></span> </a> <a href=\'\'> <span>永生玫瑰</span>");
document.writeln("                                </a> <a href=\'\'> <span>玫瑰珠宝</span>");
document.writeln("                                </a> <a href=\'\'> <span>玫瑰饰品</span>");
document.writeln("                                </a> <a href=\'\'>");
document.writeln("                                    <span>玫瑰家居</span> </a> <a href=\'\'>");
document.writeln("                                    <span>玫瑰礼品<label></label></span> </a> </div> <a class=\'menus_pic\' href=\'\'><img");
document.writeln("                                    src=\'../img/menu/ailituijian.jpg\' alt=\'roseonly 爱礼推荐\'></a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </a></li>");
document.writeln("            <li><a href=\'../html/index1.html\' class=\'topmenu_1\'>鲜花玫瑰");
document.writeln("                    <div class=\'menus2\'>");
document.writeln("                        <div class=\'menus\'>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>类型</span> <a href=\'\'> <span>玫瑰长盒<label");
document.writeln("                                            class=\'hot\'></label></span> </a> <a href=\'\'> <span>玫瑰手捧</span>");
document.writeln("                                </a> <a href=\'\'> <span>玫瑰花桶</span> </a>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>系列</span> <a href=\'\'> <span>经典永续<label");
document.writeln("                                            class=\'hot\'></label></span> </a> <a href=\'\'> <span>恒久真爱</span>");
document.writeln("                                </a> <a href=\'\'> <span>爱在满怀</span>");
document.writeln("                                </a> <a href=\'\'> <span>星座经典</span>");
document.writeln("                                </a> <a href=\'\'> <span>玫瑰公仔</span>");
document.writeln("                                </a> <a href=\'\'> <span>for all");
document.writeln("                                        love</span> </a> </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>规格</span> <a href=\'\'> <span>19支80cm<label");
document.writeln("                                            class=\'hot\'></label></span> </a> <a href=\'\'> <span>11支80cm</span> </a>");
document.writeln("                                <a href=\'\'> <span>19支40cm</span> </a>");
document.writeln("                                <a href=\'\'> <span>11支40cm</span> </a>");
document.writeln("                            </div> <a class=\'menus_pic\' href=\'\'><img src=\'../img/menu/xianhuameigui.jpg\'");
document.writeln("                                    alt=\'roseonly 鲜花玫瑰\'></a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </a></li>");
document.writeln("            <li><a href=\'../html/index1.html\' class=\'topmenu_1\'>永生玫瑰");
document.writeln("                    <div class=\'menus2\'>");
document.writeln("                        <div class=\'menus\'>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>类型</span> <a href=\'\'>");
document.writeln("                                    <span>音乐玫瑰<label></label></span> </a> <a href=\'\'> <span>玫瑰球形<label");
document.writeln("                                            class=\'hot\'></label></span> </a> <a href=\'\'> <span>玫瑰圆盒</span>");
document.writeln("                                </a> <a href=\'\'>");
document.writeln("                                    <span>玫瑰方盒</span> </a> <a href=\'\'>");
document.writeln("                                    <span>玫瑰心形盒</span> </a> </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>系列</span> <a href=\'\'>");
document.writeln("                                    <span>音乐<label></label></span> </a> <a href=\'\'> <span>玫瑰公仔<label");
document.writeln("                                            class=\'hot\'></label></span> </a> <a href=\'\'> <span>全世爱</span> </a>");
document.writeln("                                <a href=\'\'>");
document.writeln("                                    <span>经典永续<label></label></span> </a> <a href=\'\'>");
document.writeln("                                    <span>星座经典</span> </a> <a href=\'\'> <span>for all");
document.writeln("                                        love</span> </a> </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>规格</span> <a href=\'\'> <span>巨型</span>");
document.writeln("                                </a> <a href=\'\'> <span>大型<label class=\'hot\'></label></span> </a> <a href=\'\'>");
document.writeln("                                    <span>中型</span> </a> <a href=\'\'> <span>小型</span> </a> <a href=\'\'>");
document.writeln("                                    <span>Mini</span> </a> </div>");
document.writeln("                            <a class=\'menus_pic\' href=\'meigui.html\'><img src=\'../img/menu/yongshengmeigui.jpg\'");
document.writeln("                                    alt=\'roseonly 永生玫瑰\'></a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </a></li>");
document.writeln("            <li><a href=\'../html/index1.html\' class=\'topmenu_1\'>玫瑰珠宝");
document.writeln("                    <div class=\'menus2\'>");
document.writeln("                        <div class=\'menus\'>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>类型</span> <a href=\'\'> <span>项链<label");
document.writeln("                                            class=\'hot\'></label></span> </a> <a href=\'\'> <span>手链</span> </a> <a");
document.writeln("                                    href=\'\'> <span>耳饰</span> </a> <a href=\'\'> <span>手镯</span> </a> <a href=\'\'>");
document.writeln("                                    <span>戒指</span> </a>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>系列</span> <a href=\'\'> <span>loveheart");
document.writeln("                                        lock</span>");
document.writeln("                                </a> <a href=\'\'>");
document.writeln("                                    <span>玫瑰公仔<label class=\'hot\'></label></span> </a> <a href=\'\'> <span>生辰石<label");
document.writeln("                                            class=\'hot\'></label></span> </a> <a href=\'\'> <span>玫瑰经典</span>");
document.writeln("                                </a> <a href=\'\'>");
document.writeln("                                    <span>经典永续</span> </a> <a href=\'\'> <span>星座经典</span>");
document.writeln("                                </a> <a href=\'\'>");
document.writeln("                                    <span>全心全意</span> </a> <a href=\'\'>");
document.writeln("                                    <span>幸运精灵</span> </a> </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>材质</span> <a href=\'\'>");
document.writeln("                                    <span>18K金镶宝石</span> </a>");
document.writeln("                                <a href=\'\'> <span>18K白金镶钻</span> </a> <a href=\'\'> <span>18K玫瑰金镶钻</span> </a>");
document.writeln("                                <a href=\'\'> <span>18K白金</span> </a> <a href=\'\'> <span>18K玫瑰金<label");
document.writeln("                                            class=\'hot\'></label></span> </a> <a href=\'\'> <span>9K玫瑰金</span> </a>");
document.writeln("                            </div> <a class=\'menus_pic\' href=\'\'><img src=\'../img/menu/meiguizhubao.jpg\'");
document.writeln("                                    alt=\'roseonly 玫瑰珠宝\'></a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </a></li>");
document.writeln("            <li><a href=\'../html/index1.html\' class=\'topmenu_1\'>玫瑰首饰");
document.writeln("                    <div class=\'menus2\'>");
document.writeln("                        <div class=\'menus\'>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>类型</span> <a href=\'\'> <span>项链<label");
document.writeln("                                            class=\'hot\'></label></span> </a> <a href=\'\'> <span>手链</span>");
document.writeln("                                </a> <a href=\'\'> <span>耳饰</span>");
document.writeln("                                </a> </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>系列</span> <a href=\'\'> <span>玫瑰公仔</span>");
document.writeln("                                </a> <a href=\'\'> <span>玫瑰经典</span>");
document.writeln("                                </a> </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>材质</span> <a href=\'\'> <span>925银镀白金<label");
document.writeln("                                            class=\'hot\'></label></span> </a> </div> <a class=\'menus_pic\' href=\'\'><img");
document.writeln("                                    src=\'../img/menu/meiguishoushi.jpg\' alt=\'roseonly 玫瑰饰品\'></a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </a></li>");
document.writeln("            <li><a href=\'../html/index1.html\' class=\'topmenu_1\'>玫瑰家具");
document.writeln("                    <div class=\'menus2\'>");
document.writeln("                        <div class=\'menus\'>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>类型</span> <a href=\'\'> <span>散香</span>");
document.writeln("                                </a> <a href=\'\'> <span>蜡烛</span> </a> <a href=\'\'> <span>陶瓷香氛<label");
document.writeln("                                            class=\'hot\'></label></span> </a> </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>系列</span> <a href=\'\'> <span>经典永续<label");
document.writeln("                                            class=\'hot\'></label></span> </a> <a href=\'\'>");
document.writeln("                                    <span>星座经典</span> </a> <a href=\'\'> <span>for all");
document.writeln("                                        love</span> </a> </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>规格</span> <a href=\'\'> <span>单支</span>");
document.writeln("                                </a> <a href=\'\'> <span>套装礼盒<label class=\'hot\'></label></span> </a> </div> <a");
document.writeln("                                class=\'menus_pic\' href=\'\'><img src=\'../img/menu/meiguijiaju.png\'");
document.writeln("                                    alt=\'roseonly 玫瑰家居\'></a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </a></li>");
document.writeln("            <li><a href=\'../html/index1.html\' class=\'topmenu_1\'>高端定制");
document.writeln("                    <div class=\'menus2\'>");
document.writeln("                        <div class=\'menus\'>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>类型</span> <a href=\'\'> <span>高端定制系列</span>");
document.writeln("                                </a>");
document.writeln("                                <a href=\'\'>");
document.writeln("                                    <span>专属定制服务<label></label></span> </a> </div> <a class=\'menus_pic\' href=\'\'><img");
document.writeln("                                    src=\'../img/menu/gaoduandingzhi.png\' alt=\'roseonly 高端定制\'></a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </a></li>");
document.writeln("            <li><a href=\'../html/index1.html\' class=\'topmenu_1\'>诺誓世界");
document.writeln("                    <div class=\'menus2\'>");
document.writeln("                        <div class=\'menus\'>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>品牌介绍</span> <a href=\'\'> <span>品牌故事</span>");
document.writeln("                                </a> <a href=\'\'>");
document.writeln("                                    <span>产品故事</span> </a> <a href=\'\'> <span>明星时刻</span>");
document.writeln("                                </a> <a href=\'\'>");
document.writeln("                                    <span>真爱见证</span> </a> <a href=\'\'> <span>活动资讯</span>");
document.writeln("                                </a> <a href=\'\'>");
document.writeln("                                    <span>诺誓百科</span> </a> </div>");
document.writeln("                            <div class=\'number1\'><span class=\'number1_tab\'>节日百科</span> <a href=\'\'>");
document.writeln("                                    <span>情人节百科</span> </a> <a href=\'\'> <span>母亲节百科</span> </a> <a href=\'\'>");
document.writeln("                                    <span>520百科</span> </a> <a href=\'\'> <span>七夕节百科</span> </a> <a href=\'\'>");
document.writeln("                                    <span>圣诞节百科</span> </a>");
document.writeln("                            </div> <a class=\'menus_pic\' href=\'\'><img src=\'../img/menu/nuoshishijian.jpg\'");
document.writeln("                                    alt=\'roseonly 诺誓世界\'></a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </a></li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<!-- 导航栏结束 -->");